// add bootstrap css 
import 'bootstrap/dist/css/bootstrap.css'
import '../styles/globals.css'
import {createGlobalStyle} from 'styled-components'
import Head from 'next/head'
import Image from 'next/image'
import Navigation from '../components/Navigation'

const GlobalStyles = createGlobalStyle`
  html {
    --primary-color: #B0B8FB;
    --primary-color-100: #D8DCFD;
    --primary-color-200: #D3D1F3;
    --primary-color-300: #C3BCE7;
    --primary-color-400: #EEEEFF;
    --secondary-color: #FFDECA;
    --secondary-color-100: #FFE5D9;
    --secondary-color-200: #FFF2EC;
    --secondary-color-300: #FFF4ED;
    --secondary-color-400: #FFFAF6;
    --white: #ffffff;
    --white-100: #F6F7FF;
    --white-200: #F0F3FF;
    --white-200: #E9ECF5;
    --white-200: #E2E4EB;
    --black: #050517;
  }
`


function MyApp({ Component, pageProps }) {
  return (
    <>
    <GlobalStyles/>
    <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
    <Navigation />
      <main>
      <Component {...pageProps} />
      </main>
      <footer className="row text-center">
    <a href="mailto:brylyngardner@gmail.com">bryanna@bryannagardner.com</a>
  </footer>
    </>
  )
}

export default MyApp
